name: saikomakki
description: Local de Shushi Linares.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convex_bottom_bar: ^2.6.0
  parallax_image: ^0.3.1+1
  cupertino_icons: ^1.0.0
  pinch_zoom_image_last: ^0.3.2
  font_awesome_flutter: ^8.10.0
  firebase_messaging: 
  http: ^0.12.0+2
  dio: 1.0.13
  url_launcher: ^5.7.10
  flutter_staggered_grid_view: "^0.3.2"
  pinch_zoom: ^0.0.4
  galleryimage: ^1.0.2
  qr_flutter: ^3.1.0
  adaptive_dialog: ^0.9.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/img/5.png"

flutter:
  uses-material-design: true

  assets:
    - lib/img/logo.png
    - lib/img/img1.jpg
    - lib/img/img2.jpg
    - lib/img/img3.jpg
    - lib/img/img4.jpg
    - lib/img/img5.jpg
    - lib/img/img6.jpg
    - lib/img/img7.jpg
    - lib/img/img8.jpg
    - lib/img/img9.jpg
    - lib/img/img10.jpg
    - lib/img/img11.jpg
    - lib/img/img12.jpg
    - lib/img/img13.jpg
    - lib/img/img14.jpg
    - lib/img/img15.jpg
    - lib/img/img16.jpg
    - lib/img/img17.jpg
    - lib/img/img18.jpg
    - lib/img/img19.jpg
    - lib/img/img20.jpg
    - lib/img/img21.jpg
    - lib/img/img22.jpg
    - lib/img/img23.jpg
    - lib/img/FONDO.jpg
    - lib/img/LOGO-ICONOS.png
    - lib/img/BOTONES.png
    - lib/img/BTN_CARTA.png
    - lib/img/BTN_PROMO.png
    - lib/img/BTN_REDES.png
    - lib/img/gps.png
  fonts:
    - family: VWHeadB
      fonts:
        - asset: lib/fonts/VWHead-Bold.otf
    - family: VWHeadL
      fonts:
        - asset: lib/fonts/VWHead-Light.otf
    - family: VWTextB
      fonts:
        - asset: lib/fonts/VWText-Bold.otf
    - family: VWTextL
      fonts:
        - asset: lib/fonts/VWText-Light.otf        


